services:
  db:
    container_name: postgres
    image: postgres
    environment:

      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: wallet_management
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5232:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: